# Pulsar Classification using ANN
Abbie Thomas<br>
Kunho Kim<br>
May 11, 2021<br>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import warnings
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.exceptions import ConvergenceWarning

In [2]:
#Read csv file into dataframe
df = pd.read_csv(filepath_or_buffer="HTRU_2.csv",header=0)
df = df.rename(columns={"140.5625": "a", "55.68378214": "b",
                       "-0.234571412": "c", "-0.699648398": "d", 
                       "3.199832776": "e", "19.11042633": "f", 
                       "7.975531794": "g", "74.24222492": "h",
                       "0": "class"})
df = df.append({'a': 140.5625, 'b': 55.68378214, 'c': -0.234571412, 'd': -0.699648398,
               'e': 3.199832776, 'f': 19.11042633, 'g': 7.975531794, 'h': 74.24222492,
               'class': 0}, ignore_index=True)
x = df.values[:,0:-1]
y = df.values[:,-1].ravel()

# Initialise the Scaler
scaler = StandardScaler()
  
x_scaled = scaler.fit_transform(x)

type(x_scaled)

numpy.ndarray

In [3]:
#split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled = train_test_split(x_scaled, y, test_size = 0.20)

#scaler = StandardScaler()
#scaler.fit(X_train)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)


In [4]:
#Representative sample with 15% of training data being pulsar and 4% of test data being pulsars.

df0 = df.loc[df['class'] == 0]
df1 = df.loc[df['class'] == 1]

x1 = df1.iloc[:,0:-1]
y1 = df1.iloc[:,-1]

x0 = df0.iloc[:,0:-1]
y0 = df0.iloc[:,-1]


X_train0, X_test0, y_train0, y_test0 = train_test_split(x0, y0, test_size = 0.5, random_state = 0)
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1, y1, train_size = 0.80, random_state = 0)

X_train_rep = X_train1.append(X_train0)
X_test_rep = X_test1.append(X_test0)
y_train_rep = y_train1.append(y_train0)
y_test_rep = y_test1.append(y_test0)

#print(y_train_rep)
print(y_train_rep.loc[y_train_rep == 0])
print(y_test_rep.loc[y_test_rep == 0])

print(y_train_rep.loc[y_train_rep == 1])
print(y_test_rep.loc[y_test_rep == 1])

X_train_rep = scaler.fit_transform(X_train_rep)
X_test_rep = scaler.fit_transform(X_test_rep)



13041    0.0
917      0.0
16514    0.0
2132     0.0
9069     0.0
        ... 
14728    0.0
3745     0.0
11208    0.0
12288    0.0
3013     0.0
Name: class, Length: 8129, dtype: float64
3174     0.0
17622    0.0
17320    0.0
14450    0.0
17572    0.0
        ... 
15544    0.0
12820    0.0
1640     0.0
7666     0.0
9957     0.0
Name: class, Length: 8130, dtype: float64
3620     1.0
10897    1.0
3117     1.0
5679     1.0
4067     1.0
        ... 
5320     1.0
5660     1.0
9764     1.0
4104     1.0
4820     1.0
Name: class, Length: 1311, dtype: float64
13933    1.0
10904    1.0
7509     1.0
9398     1.0
4016     1.0
        ... 
8778     1.0
5080     1.0
12729    1.0
11281    1.0
400      1.0
Name: class, Length: 328, dtype: float64


In [5]:
"""
Read in data
"""
print("Reading data...")
# df = pd.read_csv('HTRU_2.csv')
df0 = pd.read_csv('data0.csv')
df1 = pd.read_csv('data1.csv')

df0 = df0.sample(n=len(df1), random_state = 0)

"""
Preprocess and data preparation
"""
print("Processing data...")

pre_features_0 = df0.iloc[: , :8]
pre_target_0 = df0['class']

# rescale variables to have 0 mean and unit variance
df_columns_0 = pre_features_0.columns
scaler = StandardScaler()
scaledf_0 = scaler.fit_transform(pre_features_0)

pre_features_1 = df1.iloc[: , :8]
pre_target_1 = df1['class']

# rescale variables to have 0 mean and unit variance
df_columns_1 = pre_features_1.columns
scaledf_1 = scaler.fit_transform(pre_features_1)

# restructure dataframe
df0 = pd.DataFrame(scaledf_0)
df0.columns = df_columns_0
df0['class'] = pre_target_0
df0['class'] = df0['class'].fillna(0).astype(np.int64)

df1 = pd.DataFrame(scaledf_1)
df1.columns = df_columns_1
df1['class'] = pre_target_1

# reassign feature and targets to newly scaled variables
features_0 = df0.iloc[:, :8]
target_0 = df0['class']

features_1 = df1.iloc[:, :8]
target_1 = df1['class']

# pre_features = df.iloc[: , :8]
# pre_target = df['class']

# # rescale variables to have 0 mean and unit variance
# df_columns = pre_features.columns
# scaler = StandardScaler()
# scaledf = scaler.fit_transform(pre_features)

# # restructure dataframe
# df = pd.DataFrame(scaledf)
# df.columns = df_columns
# df['class'] = pre_target

# # reassign feature and targets to newly scaled variables
# features = df.iloc[:, :8]
# target = df['class']

# split dataset into test and train split
# 80/20 split
feat_train_0, feat_test_0, target_train_0, target_test_0 = train_test_split(features_0, target_0, train_size = 0.8, random_state = 0)
feat_train_1, feat_test_1, target_train_1, target_test_1 = train_test_split(features_1, target_1, train_size = 0.8, random_state = 0)

feat_train = feat_train_0.append(feat_train_1)
feat_test = feat_test_0.append(feat_test_1)
target_train = target_train_0.append(target_train_1)
target_test = target_test_0.append(target_test_1)



Reading data...
Processing data...


In [6]:
df0_del = df0.iloc[0:1639, 0:-1]

X_train0, X_test0, y_train0, y_test0 = train_test_split(x0, y0, test_size = 0.2, random_state = 0)
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1, y1, train_size = 0.80, random_state = 0)

X_train_rep_del = X_train1.append(X_train0)
X_test_rep_del = X_test1.append(X_test0)
y_train_rep_del = y_train1.append(y_train0)
y_test_rep_del = y_test1.append(y_test0)

X_train_rep_del = scaler.fit_transform(X_train_rep_del)
X_test_rep_del = scaler.fit_transform(X_test_rep_del)

In [7]:
#Standard Classifier with unscaled data

mlp = MLPClassifier(hidden_layer_sizes=(8,8))
mlp.fit(X_train, y_train)

print("Training set score: %f" % mlp.score(X_train, y_train))
print("Test set score: %f" % mlp.score(X_test, y_test))

predictions = mlp.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

print("Coefficients")
print([coef.shape for coef in mlp.coefs_])


Training set score: 0.976184
Test set score: 0.975978
[[3223   23]
 [  63  271]]
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      3246
         1.0       0.92      0.81      0.86       334

    accuracy                           0.98      3580
   macro avg       0.95      0.90      0.92      3580
weighted avg       0.98      0.98      0.98      3580

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [8]:
#Standard Classifier with scaled data

mlp2 = MLPClassifier(hidden_layer_sizes=(8,8))
mlp2.fit(X_train_scaled, y_train_scaled)

print("Training set score: %f" % mlp2.score(X_train_scaled, y_train_scaled))
print("Test set score: %f" % mlp2.score(X_test_scaled, y_test_scaled))

predictions = mlp2.predict(X_test_scaled)

print(confusion_matrix(y_test_scaled,predictions))
print(classification_report(y_test_scaled,predictions))

print("Coefficients")
print([coef.shape for coef in mlp2.coefs_])

Training set score: 0.980235
Test set score: 0.979609
[[3210   11]
 [  62  297]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      3221
         1.0       0.96      0.83      0.89       359

    accuracy                           0.98      3580
   macro avg       0.97      0.91      0.94      3580
weighted avg       0.98      0.98      0.98      3580

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [9]:
#Standard Classifier with scaled data and logistic sigmoid activation function

mlp3 = MLPClassifier(hidden_layer_sizes=(8,8),activation='logistic')
mlp3.fit(X_train_scaled, y_train_scaled)

print("Training set score: %f" % mlp3.score(X_train_scaled, y_train_scaled))
print("Test set score: %f" % mlp3.score(X_test_scaled, y_test_scaled))

predictions = mlp3.predict(X_test_scaled)

print(confusion_matrix(y_test_scaled,predictions))
print(classification_report(y_test_scaled,predictions))

print("Coefficients")
print([coef.shape for coef in mlp3.coefs_])

Training set score: 0.981003
Test set score: 0.978492
[[3206   15]
 [  62  297]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      3221
         1.0       0.95      0.83      0.89       359

    accuracy                           0.98      3580
   macro avg       0.97      0.91      0.94      3580
weighted avg       0.98      0.98      0.98      3580

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [10]:
#Standard Classifier with scaled data and hyperbolic tangent activation function

mlp4 = MLPClassifier(hidden_layer_sizes=(8,8),activation='tanh')
mlp4.fit(X_train_scaled, y_train_scaled)

print("Training set score: %f" % mlp4.score(X_train_scaled, y_train_scaled))
print("Test set score: %f" % mlp4.score(X_test_scaled, y_test_scaled))

predictions = mlp4.predict(X_test_scaled)

print(confusion_matrix(y_test_scaled,predictions))
print(classification_report(y_test_scaled,predictions))

print("Coefficients")
print([coef.shape for coef in mlp4.coefs_])

Training set score: 0.980724
Test set score: 0.979050
[[3206   15]
 [  60  299]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      3221
         1.0       0.95      0.83      0.89       359

    accuracy                           0.98      3580
   macro avg       0.97      0.91      0.94      3580
weighted avg       0.98      0.98      0.98      3580

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [11]:
#Standard Classifier with scaled data and representative data

mlp5 = MLPClassifier(hidden_layer_sizes=(8,8))
mlp5.fit(X_train_rep, y_train_rep)

print("Training set score: %f" % mlp5.score(X_train_rep, y_train_rep))
print("Test set score: %f" % mlp5.score(X_test_rep, y_test_rep))

predictions = mlp5.predict(X_test_rep)

print(confusion_matrix(y_test_rep,predictions))
print(classification_report(y_test_rep,predictions))

print("Coefficients")
print([coef.shape for coef in mlp5.coefs_])

Training set score: 0.975530
Test set score: 0.931544
[[7577  553]
 [  26  302]]
              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96      8130
         1.0       0.35      0.92      0.51       328

    accuracy                           0.93      8458
   macro avg       0.67      0.93      0.74      8458
weighted avg       0.97      0.93      0.95      8458

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [12]:
#Standard Classifier with scaled data and representative data and hyperbolic tangent activation function

mlp6 = MLPClassifier(hidden_layer_sizes=(8,8),activation='tanh')
mlp6.fit(feat_train, target_train)

print("Training set score: %f" % mlp6.score(feat_train, target_train))
print("Test set score: %f" % mlp6.score(feat_test, target_test))

predictions = mlp6.predict(feat_test)

print(confusion_matrix(target_test,predictions))
print(classification_report(target_test,predictions))

print("Coefficients")
print([coef.shape for coef in mlp6.coefs_])

Training set score: 0.998856
Test set score: 1.000000
[[328   0]
 [  0 328]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       328
           1       1.00      1.00      1.00       328

    accuracy                           1.00       656
   macro avg       1.00      1.00      1.00       656
weighted avg       1.00      1.00      1.00       656

Coefficients
[(8, 8), (8, 8), (8, 1)]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [13]:
#Standard Classifier with scaled data and rep_delresentative data and hyperbolic tangent activation function

mlp7 = MLPClassifier(hidden_layer_sizes=(8,8),activation='tanh')
mlp7.fit(X_train_rep_del, y_train_rep_del)

print("Training set score: %f" % mlp7.score(X_train_rep_del, y_train_rep_del))
print("Test set score: %f" % mlp7.score(X_test_rep_del, y_test_rep_del))

predictions = mlp7.predict(X_test_rep_del)

print(confusion_matrix(y_test_rep_del,predictions))
print(classification_report(y_test_rep_del,predictions))

print("Coefficients")
print([coef.shape for coef in mlp7.coefs_])

Training set score: 0.980514
Test set score: 0.977933
[[3230   22]
 [  57  271]]
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99      3252
         1.0       0.92      0.83      0.87       328

    accuracy                           0.98      3580
   macro avg       0.95      0.91      0.93      3580
weighted avg       0.98      0.98      0.98      3580

Coefficients
[(8, 8), (8, 8), (8, 1)]


In [ ]:
#Dependencies
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import keras
from keras.models import Sequential
from keras.layers import Dense

from sklearn.metrics import accuracy_score

#dataset import
df = pd.read_csv('./project1/HTRU_2.csv') #You need to change #directory accordingly

title = list(df.columns.values)
features = title[:-1]
X = df.iloc[:, :8].values
y = df.iloc[:, 8:9].values

sc = StandardScaler()
X = sc.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

#Building ANN
model = Sequential()
model.add(Dense(8, input_dim = 8, activation = 'sigmoid'))
# model.add(Dense(8, activation = 'sigmoid'))
model.add(Dense(1, activation='sigmoid'))

#loss function and optimizer
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#training
history = model.fit(X_train, y_train, validation_data = (X_test,y_test), epochs = 100, batch_size = 64)

#testing
y_pred = model.predict(X_test)

pred = list()
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))
    
test = list()
for i in range(len(y_test)):
    test.append(np.argmax(y_test[i]))
    
#accuracy
a = accuracy_score(pred, test)
print("Accuracy:", a*100, "%")

In [15]:
# Visualize
import warnings

import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.exceptions import ConvergenceWarning

mlp2 = MLPClassifier(hidden_layer_sizes=(50,), max_iter=10, alpha=1e-4,
                    solver='sgd', verbose=10, random_state=1,
                    learning_rate_init=.1)

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ConvergenceWarning,
                            module="sklearn")
    mlp2.fit(X_train, y_train)

print("Training set score: %f" % mlp2.score(X_train, y_train))
print("Test set score: %f" % mlp2.score(X_test, y_test))

Iteration 1, loss = 12.46133428
Iteration 2, loss = 17.91379792
Iteration 3, loss = 18.05575663
Iteration 4, loss = 18.06213126
Iteration 5, loss = 18.06080540
Iteration 6, loss = 18.05957087
Iteration 7, loss = 18.05833816
Iteration 8, loss = 18.05695909
Iteration 9, loss = 18.05566317
Iteration 10, loss = 18.05434847
Training set score: 0.908856
Test set score: 0.906704
